# Generated by Django 5.0.4 on 2024-04-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultfield",
            options={
                "verbose_name": "field name",
                "verbose_name_plural": "field names",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="room name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leader_room",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="leader",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="players",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
    ]
