# Generated by Django 4.1.7 on 2024-04-18 08:56

from django.db import migrations, models
import game.models.round_result


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_defaultfield_options_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1, verbose_name="Letter")),
                (
                    "data",
                    models.JSONField(default=game.models.round_result.default_data),
                ),
            ],
        ),
    ]
