# Generated by Django 4.1.7 on 2024-04-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0003_roundresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundresult",
            name="round_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="round count"
            ),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started",
                    models.DateTimeField(auto_now_add=True, verbose_name="started"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="is finished"),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="games",
                        to="game.defaultfield",
                        verbose_name="default field",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.room",
                        verbose_name="room",
                    ),
                ),
                (
                    "round_result",
                    models.ManyToManyField(
                        blank=True,
                        related_name="games",
                        to="game.roundresult",
                        verbose_name="round result",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="winner",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
    ]
