# Generated by Django 5.0.4 on 2024-04-18 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_roundresult_round_count_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultfield",
            options={
                "verbose_name": "default_field",
                "verbose_name_plural": "default_fields",
            },
        ),
        migrations.AlterModelOptions(
            name="roundresult",
            options={
                "verbose_name": "round result",
                "verbose_name_plural": "round results",
            },
        ),
        migrations.RemoveField(
            model_name="game",
            name="round_result",
        ),
        migrations.AddField(
            model_name="roundresult",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_result",
                to="game.game",
                verbose_name="game",
            ),
        ),
        migrations.AlterField(
            model_name="defaultfield",
            name="field_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="field name"
            ),
        ),
    ]
