# Generated by Django 5.0.4 on 2024-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_defaultfield_options_alter_roundresult_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundresult",
            name="round_count",
        ),
    ]
